export {default as Home} from "./home/Home"
export {default as FranchisesPage} from "./franchises/FranchisesPage"
export {default as FranchisePage} from "./franchises/FranchisePage"
export {default as RealestatesPage} from "./realestate/RealestatesPage"
export {default as RealestatePage} from "./realestate/RealestatePage"
export {default as BlogsPage} from "./blogs/BlogsPage"
export {default as BlogPage} from "./blogs/BlogPage"
export {default as ContactUs} from "./contactus/ContactUs"
export {default as About} from "./about/About"
export {default as NotFound} from "./notfound/NotFound"

