export {default as Home} from "./home/Home"
export {default as FranchisesPage} from "./franchises/FranchisesPage"
export {default as FranchisePage} from "./franchises/FranchisePage"
export {default as ProjectPage} from "./project/ProjectPage"
export {default as ProjectsListPage} from "./project/ProjectListPage"
export {default as BlogsPage} from "./blogs/BlogsPage"
export {default as BlogPage} from "./blogs/BlogPage"
export {default as PricePage} from "./price/PricePage"
export {default as ContactUs} from "./contactus/ContactUs"
export {default as About} from "./about/About"
export {default as NotFound} from "./notfound/NotFound"

