export {default as HeroCarousel} from "./HeroCarousel"
export {default as AboutSection} from "./AboutSection"
export {default as BlogsCarouselSection} from "./BlogsCarouselSection"
export {default as ContactUsSection } from "./ContactUsSection"
export {default as ExperiencesSection} from "./ExperiencesSection"
export {default as FAQsSection} from './FAQsSection'
export {default as FeaturesSection} from "./FeaturesSection"
export {default as FeaturesSection2} from "./FeaturesSection2"
export {default as FeaturesSection3} from "./FeaturesSection3"
export {default as InformationSection} from "./InformationSection"
export {default as InstagramSection} from "./InstagramSection"
export {default as ProjectsCarouselSection} from "./ProjectsCarouselSection"
export {default as ServicesSection} from "./ServicesSection"
