import React from 'react'
import { TagInputSelect, Editor } from '../../../components'

const ProjectForm = ({
    form,
    title, 
    setTitle,
    title_fa,
    setTitle_fa,
    title_ar,
    setTitle_ar,
    title_tr,
    setTitle_tr,
    summery,
    setSummery,
    summery_fa,
    setSummery_fa,
    summery_ar,
    setSummery_ar,
    summery_tr,
    setSummery_tr,
    setFiles, 
    content,
    setContent,
    content_fa,
    setContent_fa,
    content_ar,
    setContent_ar,
    content_tr,
    setContent_tr,
    selectedTagIds,
    setSelectedTagIds,

    startingPrice,
    setStartingPrice,
    totalArea,
    setTotalArea,
    totalNumberUnits,
    setTotalNumberUnits,
    isPreSale,
    setIsPreSale,
    isInstallment,
    setIsInstallment,
    isHaveOpenPool,
    setIsHaveOpenPool,
    isHaveConveredPool,
    setIsHaveConveredPool,
    isHaveCentralAntenna,
    setIsHaveCentralAntenna,
    isHaveEmergencyPower,
    setIsHaveEmergencyPower,
    isHaveChildrenPlayground,
    setIsHaveChildrenPlayground,
    isHaveBasketballCourt,
    setIsHaveBasketballCourt,
    isHaveVolleyballCourt,
    setIsHaveVolleyballCourt,
    isHaveGym,
    setIsHaveGym,
    isHaveAirConditioningSystem,
    setIsHaveAirConditioningSystem,
    isHaveShop,
    setIsHaveShop,
    isHaveShoppingCenter,
    setIsHaveShoppingCenter,
    isHaveGreenSpace,
    setIsHaveGreenSpace,
    isHaveLobby,
    setIsHaveLobby,
    isHaveSalon,
    setIsHaveSalon,
    isHaveParking,
    setIsHaveParking,
    isHaveLaundry,
    setIsHaveLaundry,
    isHaveCafe,
    setIsHaveCafe,
    isHaveRestaurant,
    setIsHaveRestaurant,
    isHave24hSecurity,
    setIsHave24hSecurity,
    isHaveCCTV,
    setIsHaveCCTV,

    buttonLabel,
    handleSubmit 
}) => {
  return (
    <div>ProjectForm</div>
  )
}

export default ProjectForm